# pytorch_lightning==1.9.5
seed_everything: true
trainer:
  devices:
  - 0
  max_epochs: 200
  min_epochs: 100
  accelerator: gpu
  precision: 16
  accumulate_grad_batches: 3
  auto_lr_find: false
  profiler: null

  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: 'ckpt/exp3_cosine_loss_new_data'
      name: ''
      version: ''

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ${trainer.logger.init_args.save_dir}
        filename: '{epoch}-{train_loss:.3f}-{val_loss:.3f}-{train_acc:.3f}-{val_acc:.3f}'
        monitor: val_acc
        save_top_k: 3
        mode: max
        every_n_epochs: 1
        auto_insert_metric_name: true

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ${trainer.callbacks[0].init_args.monitor}
        patience: 15
        mode: ${trainer.callbacks[0].init_args.mode}

    - class_path: RichProgressBar
      init_args:
        leave: true

    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    
    - class_path: RichModelSummary
      init_args:
        max_depth: 1

  overfit_batches: 0.0
  fast_dev_run: false
  log_every_n_steps: 3
  check_val_every_n_epoch: 1
  auto_scale_batch_size: false
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_processes: null
  track_grad_norm: -1
  val_check_interval: null
  num_sanity_val_steps: 2
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  detect_anomaly: false
  plugins: null
  amp_backend: null
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true

model:
  model: 
    class_path: model.Net
    init_args:
      input_size: 384
      hidden_size: 384
      output_size: 384
  learning_rate: 0.001
  threshold: 0.4
  criterion:
    class_path: torch.nn.CosineEmbeddingLoss
    init_args:
      margin: 0


data:
  train_pkl_fp: train_pairs.pkl
  val_pkl_fp: val_pairs.pkl
  test_pkl_fp: test_pairs.pkl
  predict_pkl_fp: test_pairs.pkl
  data_cfg:
    feat_dim: 384
  training_cfg: 
    bs: 128
    shuffle_train: True
    num_workers: 8


save_config_overwrite: false
save_config_callback: ''
ckpt_path: null
